name: Sync cards from Google

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # every hour

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build lean cards
        run: node scripts/build_cards.js
      - name: Commit generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/campaigns.cards.min.json
          git commit -m "Update cards feed from Google" || echo "No changes"
          git push
      - name: Purge jsDelivr cache
        run: |
          curl -s "https://purge.jsdelivr.net/gh/Jrosai-dev/fundlibraries-campaigns@main/public/campaigns.cards.min.json"
