name: Sync cards from Google

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *'  # every hour

permissions:
  contents: write

concurrency:
  group: cards-sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure repo is up to date
        run: |
          set -euo pipefail
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: Clean old versioned folders
        run: rm -rf public/campaigns.v-*

      - name: Build cards (canonical + versioned + index + per‑slug + manifest + home + feeds pointer)
        run: node scripts/build_cards.js

      - name: Commit generated files
        id: commit
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A public
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          git commit -m "Update cards feed from Google"
          git push origin HEAD:main
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Purge jsDelivr caches
        if: steps.commit.outputs.changed == 'true'
        run: |
          set -euo pipefail
          purge() { for i in 1 2 3; do curl -fsS "$1" && return 0 || sleep 2; done; return 1; }

          purge https://purge.jsdelivr.net/gh/Jrosai-dev/fundlibraries-campaigns@main/public/feeds.latest.json || true
          purge https://purge.jsdelivr.net/gh/Jrosai-dev/fundlibraries-campaigns@main/public/cards.latest.json || true

          purge https://purge.jsdelivr.net/gh/Jrosai-dev/fundlibraries-campaigns@main/public/campaigns.cards.min.json || true
          purge https://purge.jsdelivr.net/gh/Jrosai-dev/fundlibraries-campaigns@main/public/campaigns.index.min.json || true
          purge https://purge.jsdelivr.net/gh/Jrosai-dev/fundlibraries-campaigns@main/public/campaigns.home.min.json || true
          purge https://purge.jsdelivr.net/gh/Jrosai-dev/fundlibraries-campaigns@main/public/campaigns.manifest.json || true

          VERSIONED_URL=$(node -e "console.log(require('./public/cards.latest.json').url)")
          PURGE_URL="${VERSIONED_URL/cdn.jsdelivr.net\/gh/purge.jsdelivr.net\/gh}"
          purge "$PURGE_URL" || true

      - name: Done
        run: echo "Sync finished. CDN verification is disabled due to environment restrictions."
